// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Pakai satu nama konsisten
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL!;
const SUPABASE_PUBLISHABLE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwanNmc2Ztd2trc3FmaW5lbm9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzUwNzgsImV4cCI6MjA3MDIxMTA3OH0.gSmVyXfFRwgM5RL80vHuANrV5ZWV26iSGI9Di_3fMxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Tambahkan default export supaya import lama `import supabase from ...` tetap jalan
export default supabase;
